# Generated by Django 3.1.8 on 2021-05-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video_id',
            field=models.SlugField(default=None),
            preserve_default=False,
        ),
    ]
